version: "3.7"
services:
  db:
    image: mysql:5.7.17
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=root123"
      - "MYSQL_DATABASE=beek_test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test123"
    volumes:
      - ./data/db_schemas:/docker-entrypoint-initdb.d
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    image: puckel/docker-airflow:latest
    restart: always
    depends_on: 
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./data/output_data:/home/airflow/data
    ports:
      - "6060:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 1m30s
      timeout: 30s
      retries: 5